name: sirius
description: A powerful Dart backend framework for building scalable APIs.
version: 1.0.0
homepage: https://github.com/sirius-technology/sirius_dart

environment:
  sdk: ^3.6.1

dependencies:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0