name: sirius_backend
description: >
  Sirius is a lightweight yet powerful Dart backend framework designed for building fast, scalable, and structured HTTP & WebSocket APIs.

version: 2.3.6

homepage: https://github.com/sirius-technology/sirius_dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0 