name: sirius_backend
description: A powerful Dart backend framework for building scalable APIs.
version: 1.0.7
homepage: https://github.com/sirius-technology/sirius_dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0