name: sirius_backend
description: >
  Sirius is a lightweight yet powerful Dart backend framework designed for building fast, scalable, and structured HTTP & WebSocket APIs. 
  It provides clean routing, middleware support, request validation, and real-time WebSocket communication.

version: 2.2.2
homepage: https://github.com/sirius-technology/sirius_dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0 